### ISSUE TITLE
Support SingleRowMode?

### ISSUE THREAD

**Issue by fbrosda** [kahua/Gauche-dbd-pg#2]
Hi,

first of all thanks for all the cleanup you made :+1: 

After using this package a bit, I got into trouble when the SQL result is to large, to be accumulated in one PGresult. Therefore I had a look at https://www.postgresql.org/docs/current/libpq-single-row-mode.html

A first quick implementation with support for retrieving results row-by-row can be found here: https://github.com/fbrosda/Gauche-dbd-pg/commit/6954d30e3e005881f6184508fb3e0d646fe79a88 Before creating a pull request I wanted to ask, if you are interested in extending the package in this way at all?

**Comment by shirok** [comment]
Hi there,
I added `pq-send-query` and `pq-get-result` for the starter.  They're low-level interface than dbd, and you need to deal with raw connection and result (see the added tests).    Let me know if they're feasible, and other APIs you need if there's more.

**Comment by fbrosda** [comment]
Hi, 

thanks for the additions. In general it should be feasible, to work with this API. What's missing is at least `PQsetSingleRowMode` (maybe like this: https://github.com/fbrosda/Gauche-dbd-pg/commit/5d0ae2c96d28814ea61e65e756bcc11ff6f1803f).

Based on the official documentation about [SingleRowMode](https://www.postgresql.org/docs/current/libpq-single-row-mode.html),  there is quite a bit of work involved in getting all the results and cleaning everything up correctly, including calling `pq-get-result` multiple times, after the last actual row was returned.

Personally I think it would be nice, to have a simple way to `map` over all the rows regardless if single-row-mode is used or not. But I have no idea, if anyone besides me would want to use this, so it's totally fine, to stick with the low level functions for now and I implement any convenience wrappers I want to have around it on my side. Of course I can share them then if anyone would be interested.

**Comment by shirok** [comment]
I added `pq-set-single-row-mode`.   I'm not familiar with PostgreSQL API enough to see if it's working properly, though.  See the test code here https://github.com/kahua/Gauche-dbd-pg/blob/master/test/test.scm#L99 ; I thought `pq-get-result` would return `#f` after all rows are retrieved (If PQgetResult returns NULL, it is converted to `#f`), but it seems to return a `<pg-result>` with zero rows.  I'm not sure if ti is how it's supposed to work.

**Comment by fbrosda** [comment]
@shirok That's how it is supposed to work. From the official docs:

> After the last row, or immediately if the query returns zero rows, a zero-row object with status PGRES_TUPLES_OK is returned

Afterwards you need to call get-result unitl it returns null:

> But note that it is still necessary to continue calling [PQgetResult](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQGETRESULT) until it returns null.

That's the part, where I think it would be nice if it's hidden away, so as a user you don't have to deal with it for each query.

**Comment by shirok** [comment]
Ah, thanks.  I changed the test to follow the protocol.
Certainly it is nice to have a wrapper.  Since this is Postgres specific, it'll still be pq-* level procedure, not in DBI level.
If we do so, I'd like to support all pq-send-query families (pq-send-query-params etc.) and I'm thinking how to deal with `Oid*` arguments.

**Comment by fbrosda** [comment]
Looks good so far, thank you. I'll adjust my code based on this and let you know how far I get.

**Comment by fbrosda** [comment]
Just a short follow up. Used the current version a bit now and it works fine.  I added a small wrapper on my side, to make looping over the results a bit simpler, but I'm not sure if it makes much sense, to add it to the library. Here it is:

```scheme
(define (pq-single-row-for-each h proc)
  (let1 r (pq-set-single-row-mode h)
    (unless (= 1 r)
      (error "PQsetSingleRowMode failed:" r))
    (while (pq-get-result h) => res
      (let1 s (pq-result-status res)
	(cond [(= s PGRES_SINGLE_TUPLE)
	       (proc res)]
	      [(= s PGRES_TUPLES_OK)
	       '()]
	      [else
	       (error "Error processing PGresult:"
		      (pq-result-error-message res))])))))
```

Which can then be used like this:

```scheme
(let1 h (pg-connection-handle conn)
  (pq-send-query h query)
  (pq-single-row-for-each h do-something))
```

From my side, this is currently sufficient, to access the postgres db. The rest of the `PQsend*` api might be nice, but is not really necessary. Maybe I play around a bit, when I find some time. So far thanks a lot for the good work :+1:

**Comment by shirok** [comment]
I'd provide `fold`-type interface as a basis rather than `for-each`, for you can derive `map` and `for-each` from `fold` easily.
A greater issue is that the call changes the status (single row mode) of the connection.  We can state that as a part of API, but my hunch is that it's better to contain the state change in a function; e.g. revert the mode upon completion of the function or error.

**Comment by fbrosda** [comment]
Going from `for-each` to `fold` is a good remark.  Furthermore if everything works fine, we don't need to worry about the state change, as single-row-mode only affects the current query:

> This mode selection is effective only for the currently executing query. [link](https://www.postgresql.org/docs/current/libpq-single-row-mode.html)

The tricky bit is the part, when some error happens:

> A client that uses [PQsendQuery](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQSENDQUERY)/[PQgetResult](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQGETRESULT) can also attempt to cancel a command that is still being processed by the server; see [Section 34.7](https://www.postgresql.org/docs/current/libpq-cancel.html). But regardless of the return value of [PQcancel](https://www.postgresql.org/docs/current/libpq-cancel.html#LIBPQ-PQCANCEL), the application must continue with the normal result-reading sequence using [PQgetResult](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQGETRESULT). A successful cancellation will simply cause the command to terminate sooner than it would have otherwise.

My current approach was to catch everything inside `proc` and simply skip rows, which produce some problems. But here is a second try, for a generic version, that cleans up leftover state:

```scheme
(define (pq-fold-row kons knil conn)
  (unless (= 1 (pq-set-single-row-mode conn))
    (error "PQsetSingleRowMode failed"))
  (let ((seed knil)
	(err #f))
    (while (pq-get-result conn) => row
      (unless err
	(let1 status (pq-result-status row)
	  (cond [(= status PGRES_SINGLE_TUPLE)
		 (guard (e [else
			    (receive (status msg) (pq-cancel (pq-get-cancel conn))
			      (if (= 1 status)
				(set! err e)
				(error <serious-condition> "Could not cancel query" msg)))])
		   (set! seed (kons row seed)))]
		[(= status PGRES_TUPLES_OK)
		 seed]
		[else
		 (set! err (make-error (pq-result-error-message row)))]))))
    (if err
      (raise err)
      seed)))
```

In case some error happens, the query will be canceled, but the error is only raised after all leftover rows are consumed. 

Should I put this into a merge request (and also add some tests)?
